#!/usr/bin/env python
"""sync_engine.py - one-way, allowlisted, versioned export of the personal study engine into the product.

    python product/tools/sync_engine.py            # copy what changed (personal -> product), report
    python product/tools/sync_engine.py --check    # exit 1 when the product copy drifted from the personal tools
    python product/tools/sync_engine.py --force    # overwrite a hand-edited vendored copy (drift) - say why in the commit

Rules (collab 2026-09-12, partner IMPROVE adopted): the personal tools are the source of truth; a vendored copy is never
edited by hand - a product-only need goes into an adapter in engine/studycore/, an engine improvement goes into the
personal tool first. The manifest lists every file that may travel and every file that must not (credentials, personal
records, anything acting in the owner's name). A sha256 ledger (vendor/LEDGER.json) records what was copied, when, and
from which manifest version, so drift on either side is visible: personal newer -> "behind", vendored edited -> "DRIFT".
"""
from __future__ import annotations

import hashlib
import json
import shutil
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
PRODUCT = HERE.parent
MANIFEST = HERE / "engine-manifest.json"


def sha(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()[:16]


def main(argv: list[str]) -> int:
    m = json.loads(MANIFEST.read_text(encoding="utf-8"))
    src = (HERE / m["source"]).resolve()
    dst = (PRODUCT / m["target"]).resolve()
    dst.mkdir(parents=True, exist_ok=True)
    ledger_p = dst / "LEDGER.json"
    ledger = json.loads(ledger_p.read_text(encoding="utf-8")) if ledger_p.exists() else {"version": None, "files": {}}
    check, force = "--check" in argv, "--force" in argv
    copied, behind, drift, missing = [], [], [], []
    for name in m["files"]:
        s, d = src / name, dst / name
        if name in m["excluded"]:
            raise SystemExit(f"manifest lists {name} both as file and as excluded")
        if not s.exists():
            missing.append(name); continue
        s_hash = sha(s)
        rec = ledger["files"].get(name)
        d_hash = sha(d) if d.exists() else None
        if d_hash and rec and d_hash != rec["sha"]:
            drift.append(name)   # the vendored copy was edited by hand
            if not force:
                continue
        if d_hash == s_hash:
            continue
        behind.append(name)
        if not check:
            shutil.copy2(s, d)
            ledger["files"][name] = {"sha": s_hash, "copiedAt": time.strftime("%Y-%m-%dT%H:%M:%S"), "manifest": m["version"]}
            copied.append(name)
    for name in list(ledger["files"]):
        if name not in m["files"]:
            (dst / name).unlink(missing_ok=True); del ledger["files"][name]
    ledger["version"] = m["version"]
    if not check:
        ledger_p.write_text(json.dumps(ledger, indent=1), encoding="utf-8")
        (dst / "__init__.py").write_text('"""Vendored copies of the personal study tools - generated by product/tools/sync_engine.py, never edited here."""\n', encoding="utf-8")
    print(f"ENGINE SYNC {m['version']}: {len(copied)} copied, {len(behind) - len(copied)} behind, {len(drift)} drift, {len(missing)} missing")
    for n in drift:
        print(f"  DRIFT {n}: the vendored copy was edited by hand - move the change into ../tools/{n} or an adapter, then --force")
    for n in missing:
        print(f"  MISSING {n} in {src}")
    if check and (behind or drift):
        for n in behind:
            print(f"  BEHIND {n}: run python product/tools/sync_engine.py")
        return 1
    return 1 if drift and not force else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
